steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/webcam-demo', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/webcam-demo']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'webcam-demo', '--image', 'gcr.io/$PROJECT_ID/webcam-demo', '--region', 'europe-west1', '--platform', 'managed', '--allow-unauthenticated']
